services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
      - '8080:80'
      - '8443:443'
      - '2019:2019'
    volumes:
      - ./html:/srv
      - ./caddy-config/data:/data
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    restart: unless-stopped
    networks:
      - pg_network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres
    volumes:
      - ./postgres/servers.json:/pgadmin4/servers.json
    networks:
      - pg_network

networks:
  pg_network:

volumes:
  postgres_data: